---
permalink: san-migration/concept_target_and_initiator_port_zoning.html 
sidebar: sidebar 
keywords: target, initiator, port, zoning 
summary: FLI 迁移要求 NetApp 存储访问源存储 LUN 。这是通过使用目标存储的启动程序端口对源存储的目标端口进行分区来实现的。 
---
= ONTAP FLI 迁移的目标和启动器端口分区
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI 迁移需要NetApp存储能够访问外部阵列源 LUN。这可以通过将源存储的目标端口与NetApp目标存储的启动器端口进行分区来实现。

现有源存储到主机分区不会进行修改，并且会在迁移后停用。创建主机到目标存储分区，以使主机能够从目标存储访问迁移的 LUN 。

使用 FLI 的标准迁移方案需要四个不同的分区：

* 区域 1 ：源存储到目标存储（生产网络结构 A ）
* 区域 2 ：源存储到目标存储（生产网络结构 B ）
* 区域 3 ：主机到目标存储（生产网络结构 A ）
* 区域 4 ：主机到目标存储（生产网络结构 B ）


请遵循以下分区最佳实践：

* 请勿在同一分区中混用源存储目标端口和目标存储目标端口。
* 请勿在同一分区中混用目标存储启动程序端口和主机端口。
* 请勿在同一分区中混用目标存储目标端口和启动程序端口。
* 每个控制器至少具有两个端口的分区，以实现冗余。
* NetApp 建议使用单个启动程序和单个目标分区。


[NOTE]
====
使用目标存储启动程序端口对源存储目标端口进行分区后，可以使用 storage array show 命令在目标存储中看到源存储。首次发现存储阵列时， NetApp 控制器可能不会自动显示该阵列。通过重置连接了 ONTAP 启动程序端口的交换机端口来修复此问题。

====
使用 FLI 的标准迁移方案需要四个不同的分区。您应在每个分区中包含特定端口。

* 区域 1 ：源存储到目标存储（生产网络结构 A ）
+
分区 1 应包含所有节点上的所有目标存储启动程序以及网络结构 A 中的所有源存储目标端口区域成员包括：

+
** ONTAP — Node1 — 0a
** ONTAP — Node2 — 0a
** AMS2100 — Ctrl0 — 0a
** AMS2100 — Ctrl1 — 1a


* 区域 2 ：源存储到目标存储（生产网络结构 B ）
+
分区 2 应包含所有节点上的所有目标存储启动程序端口以及网络结构 B 中的所有源存储目标端口区域 2 成员包括：

+
** ONTAP — Node1 — 0b
** ONTAP — Node2 — 0b
** AMS2100 — Ctrl0 — 0e
** AMS2100 — Ctrl1 — 1e


* 区域 3 ：主机到目标存储（生产网络结构 A ）
+
分区 3 应包含主机总线适配器（ HBA ）端口 1 和生产网络结构 A 中的目标控制器端口区域 3 成员包括：

+
** ONTAP — lif1
** ONTAP — LIF3
** host — HBA0


* 区域 4 ：主机到目标存储（生产网络结构 B ）
+
分区 4 应包含生产网络结构 B 中的 HBA 端口 2 和目标控制器端口区域 4 成员包括：

+
** ONTAP — LIF2
** ONTAP — LIF4
** host — HBA1



