---
permalink: san-migration/reference_clearing_scsi_3_persistent_reservations.html 
sidebar: sidebar 
keywords: clear, scsi-3, persistent, reservations 
summary: 如果您使用的是 Windows 集群，则需要删除仲裁磁盘的 SCSI-3 预留，即使所有集群主机均脱机也是如此。 
---
= 清除 SCSI-3 持久预留
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是 Windows 集群，则需要删除仲裁磁盘的 SCSI-3 预留，即使所有集群主机均脱机也是如此。

如果尝试将源 LUN 标记为外部磁盘，则会显示以下错误消息：

 Error: command failed: The specified foreign disk has SCSI persistent reservations. Disk serial number: "6006016021402700787BAC217B44E411". Clear the reservation using the "storage disk remove-reservation" command before creating the import relationship.
您可以使用 `storage disk remove-reservation` 命令删除 NetApp 控制器上仲裁磁盘的 SCSI-3 预留：

[listing]
----
storage disk remove-reservation –disk disk_name
----
下面是一个显示此错误及其修复方法的代码片段：

[listing]
----
cluster-4b::*> lun offline -vserver fli_cluster -path /vol/fli_volume/cluster_CVS
cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_CVS -foreign-disk 6006016021402700787BAC217B44E411
Error: command failed: The specified foreign disk is not marked as foreign. Disk serial number: "6006016021402700787BAC217B44E411".

cluster-4b::*> sto disk show -disk DGC-1.6 -fields serial-number,is-foreign
 (storage disk show)
disk is-foreign serial-number
------- ---------- --------------------------------
DGC-1.6 true 6006016021402700787BAC217B44E411

cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_CVS -foreign-disk 6006016021402700787BAC217B44E411

Error: command failed: The specified foreign disk has SCSI persistent reservations. Disk serial number: "6006016021402700787BAC217B44E411". Clear the reservation using the "storage disk remove-reservation" command before creating the import relationship.

cluster-4b::*> storage disk remove-reservation -disk DGC-1.6
cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_CVS -foreign-disk 6006016021402700787BAC217B44E411
cluster-4b::*> lun online -vserver fli_cluster -path /vol/fli_volume/cluster_CVS
cluster-4b::*> lun import show

vserver foreign-disk path operation admin operational percent in progress state state complete
 -------------------------------------------------------------------------------
fli_cluster 6006016021402700787BAC217B44E411 /vol/fli_volume/cluster_CVS import stopped stopped 0

cluster-4b::*> lun import start -vserver fli_cluster -path /vol/fli_volume/cluster_CVS
cluster-4b::*> lun import show

vserver foreign-disk path operation admin operational percent in progress state state complete
-------------------------------------------------------------------------------
fli_cluster 6006016021402700787BAC217B44E411 /vol/fli_volume/cluster_CVS import started in_progress 7
----