---
permalink: san-migration/remove-lun-import-relationship-offline.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 验证作业是可选的，但建议使用。它对源 LUN 和目标 LUN 进行了按块比较。验证作业所需时间几乎与迁移时间相同或稍长。 
---
= ONTAP FLI 离线迁移后删除 LUN 导入关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部 LUN 导入 (FLI) 脱机迁移完成后，可以安全地移除 LUN 导入关系。此时，主机正在访问新的NetApp阵列，执行对新ONTAP LUN 的所有 I/O，并且源 LUN 不再使用，因此不再需要导入关系。

从ONTAP9.17.1 开始，支持使用 FLI 离线迁移对外来 LUN 进行数据迁移，具体方法如下 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 系统"^].ASA r2 系统与其他ONTAP系统（ASA、 AFF和FAS）在存储层实现方面有所不同。ASA r2 系统中，创建存储单元（LUN 或命名空间）时会自动创建卷。每个卷仅包含一个存储单元。因此，对于ASA r2 系统，您无需在 `-path`创建 LUN 时，请提供此选项；您应该包含存储单元路径。

.步骤
. 删除导入关系以移除数据导入作业。
+
[source, cli]
----
lun import delete -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此示例显示用于删除 *winvol* 卷和 *datamig* SVM 中名为 *bootlun*、*fdrive* 和 *gdrive* 的 LUN 的导入关系的命令。

+
[listing]
----
DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/gdrive
----
. 验证导入作业是否已被删除。
+
[source, cli]
----
lun import show -vserver <SVM_name>
----
+
此示例显示用于验证是否已删除 *datamig* SVM 的导入作业的命令。

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig
There are no entries matching your query.
----
. 将外部 LUN 属性标记为 `false` 。
+
[source, cli]
----
storage disk modify -serial-number <serial_number> -is-foreign false
----
+
此示例显示将外部 LUN 属性标记为 `false`对于 *winvol* 卷和 *datamig* SVM 中名为 *bootlun*、*fdrive* 和 *gdrive* 的 LUN。

+
[listing]
----
DataMig-ontap::*> storage disk modify { -serial-number 83017542001E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000F }
-is-foreign false
----
. 验证外部 LUN 是否标记为 `false` 。
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner, import-in-progress, is-foreign
----
+
此示例显示用于验证外部 LUN 是否标记为 `false`在 *HITACHI_DF600F_1* 阵列上。

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     false      unassigned     false              83017542001E
HIT-1.3  -     false      unassigned     false              83017542000E
HIT-1.4  -     false      unassigned     false              83017542000F
3 entries were displayed.
----
. 使目标 LUN 联机。
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此示例显示使 *winvol* 卷和 *datamig* SVM 中名为 *bootlun*、*fdrive* 和 *gdrive* 的 LUN 的目标 LUN 联机的命令。

+
[listing]
----
DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/gdrive
----
. 验证 LUN 是否联机。
+
[source, cli]
----
lun show -vserver <SVM_name>
----
+
此示例显示用于验证 *datamig* SVM 的 LUN 是否在线的命令。

+
[listing]
----
DataMig-ontap::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  mapped   vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  mapped   linux         2GB
datamig   /vol/esxvol/solrdmplun          online  mapped   solaris       2GB
3 entries were displayed.
----
. 或者，查看事件日志以验证迁移结果。
+
[source, cli]
----
event log show –event fli*
----
+
此示例显示用于查看 FLI 迁移结果的事件日志的命令的示例输出。

+
[listing]
----
DataMig-ontap::*> event log  show –event fli*

7/7/2014 18:37:21   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
7/7/2014 18:37:15   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
7/7/2014 18:02:21   DataMig-ontap-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


.下一步是什么？
link:concept_fli_offline_post_migration_tasks.html["执行 FLI 离线迁移的迁移后任务"] 。
