---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 验证作业是可选的，但建议使用。它对源 LUN 和目标 LUN 进行了按块比较。验证作业所需时间几乎与迁移时间相同或稍长。 
---
= 验证ONTAP FLI 离线迁移结果
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将 LUN 从外部阵列迁移到ONTAP存储系统后，FLI 可以对源 LUN 和目标 LUN 进行逐块比较，以验证迁移是否完整准确。迁移验证所需的时间与迁移过程大致相同（或略长）。

不需要进行迁移验证，但强烈建议进行。

.关于此任务
从ONTAP9.17.1 开始，支持使用 FLI 离线迁移对外来 LUN 进行数据迁移，具体方法如下 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 系统"^].ASA r2 系统与其他ONTAP系统（ASA、 AFF和FAS）在存储层实现方面有所不同。ASA r2 系统中，创建存储单元（LUN 或命名空间）时会自动创建卷。每个卷仅包含一个存储单元。因此，对于ASA r2 系统，您无需在 `-path`创建 LUN 时，请提供此选项；您应该包含存储单元路径。

.步骤
. 开始LUN迁移验证。
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此示例显示用于启动 *winvol* 卷和 *datamig* SVM 中名为 *bootlun*、*fdrive* 和 *gdrive* 的 LUN 迁移验证的命令。

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. 监控验证状态。
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
此示例显示用于监控 *datamig* SVM 的验证状态的命令。

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
您可以执行相同的命令来跟踪验证进度。验证作业成功完成后，*operational-state* 将显示 *completed* 状态。

. 停止 LUN 验证。
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
此示例显示停止 *datamig* SVM 的 LUN 验证的命令。

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
必须先明确停止 LUN 导入验证，然后才能将 LUN 恢复联机。否则，  `lun online`命令失败。即使状态显示验证已完成，也必须手动执行此步骤。



.下一步是什么？
link:remove-lun-import-relationship-offline.html["解除LUN导入关系"] 。
